version: '3'

services:
  litematic-viewer:
    build: .
    container_name: litematic-viewer
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./src/uploads:/app/src/uploads:rw,z
      - ./src/outputs:/app/src/outputs:rw,z
    environment:
      - NODE_ENV=production
    user: "1000:1000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    shm_size: 1g 